apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderate-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderate
  template:
    metadata:
      labels:
        app: moderate
    spec:
      containers:
        - name: moderate
          image: blog/moderate:0.0.2