apiVersion: v1
kind: Service
metadata:
  name: moderate-service
spec:
  type: ClusterIP
  selector:
    app: moderate
  ports:
    - name: moderate
      protocol: TCP
      port: 4003
      targetPort: 4003